{
  description = "Rust Compiler with LLVM 18";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    rust-overlay.url = "github:oxalica/rust-overlay";
    crane.url = "github:ipetkov/crane";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, rust-overlay, crane, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs { inherit system overlays; };
        
        # Rust toolchain via overlay
        rustToolchain = pkgs.rust-bin.stable.latest.default.override {
          extensions = [ "rust-src" "rust-analyzer" "clippy" "rustfmt" ];
        };

        # Crane instantiated with our specific toolchain
        craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;

        # LLVM 18 setup
        llvm = pkgs.llvmPackages_18;
        
        # Build-time tools (host tools needed during compilation, not at runtime)
        commonNativeBuildInputs = with pkgs; [
          pkg-config
          cmake
        ];

        # Runtime/link-time dependencies
        commonBuildInputs = with pkgs; [
          llvm.llvm
          llvm.libclang
          llvm.clang   # expõe `lli` e `clang` no shell para inspecionar IR manualmente
          llvm.bintools
          libffi
          zlib
          ncurses      # exigido por certas features do LLVM no linking
          libxml2
        ];

        commonEnv = {
          LIBCLANG_PATH = "${llvm.libclang.lib}/lib";
          LLVM_SYS_180_PREFIX = "${llvm.llvm.dev}";
        };

      in
      {
        # Final package build with native cache support (for Nix)
        packages.default = craneLib.buildPackage (commonEnv // {
          src = craneLib.cleanCargoSource ./.;
          strictDeps = true;
          nativeBuildInputs = commonNativeBuildInputs;
          buildInputs = commonBuildInputs;
        });

        # Development environment (for using `nix develop` and running `cargo run`)
        devShells.default = pkgs.mkShell (commonEnv // {
          inputsFrom = [ self.packages.${system}.default ];
          nativeBuildInputs = commonNativeBuildInputs;
          buildInputs = commonBuildInputs ++ [ rustToolchain ];

          shellHook = ''
            echo "--- PBLang Development Environment ---"
            echo "Rust:  $(rustc --version)"
            echo "LLVM:  $(llc --version | head -1)"
            echo "Tip: Use 'lli <file.ll>' to execute the IR generated by the compiler."
            export RUST_BACKTRACE=1
          '';
        });
      });
}
